name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 8
        cache: maven
    - name: Build
      run: |
        mvn -B package --file pom.xml
        mkdir staging
        cp vmagic*/target/*.jar staging
    - name: Save the jars
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: staging

  # Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts
    - name: Update vmagic-parser dependency graph
      uses: advanced-security/maven-dependency-submission-action@v4
      with:
        directory: vmagic-parser
    - name: Update vmagic dependency graph
      uses: advanced-security/maven-dependency-submission-action@v4
      with:
        directory: vmagic
